# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ed_classification'
version: '0.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

vars:
    ed_classification_encounter_override: medicare_lds_five_percent.core.encounter
    ed_classification_condition_override: medicare_lds_five_percent.core.condition
    encounter: >
        {% if var('ed_classification_encounter_override',none) is not none %}{{var('ed_classification_encounter_override')}}
        {%- elif var('core_encounter_override',none) is not none %}{{var('core_encounter_override')}}
        {%- else %}{{ref('claims_preprocessing__encounter')}}
        {%- endif %}
    condition: >
        {% if var('ed_classification_condition_override',none) is not none %}{{var('ed_classification_condition_override')}}
        {%- elif var('core_condition_override',none) is not none %}{{var('core_condition_override')}}
        {%- else %}{{ref('claims_preprocessing__condition')}}
        {%- endif %}

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  ed_classification: # you must include the project name
    +schema: seed_data
    johnston_icd9:
      +column_types:
        icd9: text
    johnston_icd10:
      +column_types:
        icd10: text
